number_in_letter = [
    "",
    "premier",
    "deuxième",
    "troisième",
    "quatrième",
    "cinquième",
    "sixième",
    "septième",
    "huitième",
    "neuvième",
    "dixième",
    "onzième",
    "douzième",
    "treizième",
    "quatorzième",
    "quinzième",
    "seizième",
    "dix-septième",
    "dix-huitième",
    "dix-neuvième",
    "vingtième",
    "vingt-et-unième",
    "vingt-deuxième",
    "vingt-troisième",
    "vingt-quatrième",
    "vingt-cinquième",
    "vingt-sixième",
    "vingt-septième",
    "vingt-huitième",
    "vingt-neuvième",
    "trentième",
    "trent-et-unième",
    "trent-deuxième",
    "trent-troisième",
    "trent-quatrième",
    "trent-cinquième",
    "trent-sixième",
    "trent-septième",
    "trent-huitième",
    "trent-neuvième",
    "quarantième",
    "quarantième et unième",
    "quarantième et deuxième",
    "quarantième et troisième",
    "quarantième et quatrième",
    "quarantième et cinquième",
    "quarantième et sixième",
    "quarantième et septième",
    "quarantième et huitième",
    "quarantième et neuvième",
    "cinquantième",
    "cinquantième et unième",
    "cinquantième et deuxième",
    "cinquantième et troisième",
    "cinquantième et quatrième",
    "cinquantième et cinquième",
    "cinquantième et sixième",
    "cinquantième et septième",
    "cinquantième et huitième",
    "cinquantième et neuvième",
    "soixantième",
    "soixantième et unième",
    "soixantième et deuxième",
    "soixantième et troisième",
    "soixantième et quatrième",
    "soixantième et cinquième",
    "soixantième et sixième",
    "soixantième et septième",
    "soixantième et huitième",
    "soixantième et neuvième",
    "soixante-dixième",
    "soixante-dixième et unième",
    "soixante-dixième et deuxième",
    "soixante-dixième et troisième",
    "soixante-dixième et quatrième",
    "soixante-dixième et cinquième",
    "soixante-dixième et sixième",
    "dernier",
]
